# This cloudFormation templates create a VPC,Subnet,Routetable, SG and EC2 in a given subnet


AWSTemplateFormatVersion: 2010-09-09
Description: First Tempate for creating an EC2 instance

Parameters:
  "EC2_Name":
    Type: String 
    Description: Name of Instance    

Resources: # This cloudFormation templates create a VPC,Subnet,Routetable, SG and EC2 in a given subnet
  VPC:

    Type: AWS::EC2::VPC
    Description: VPC to host the resources
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        -
          Key: Name
          Value: MyFirstVPCThroughCFTemplate
  
  VPCSubnet:
    Type: AWS::EC2::Subnet
    Description: Subnet to host Devices
    Properties:
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true
      'VpcId': !Ref VPC

  VPCRouteTable:
    Type: AWS::EC2::RouteTable
    Description: Routetable for VPC
    Properties:
      VpcId: !Ref VPC
     
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Description: Internetgateway for VPC
    Properties:
      Tags: 
        -
          Key: Name
          Value: Internetgateway for VPC

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Description: Attaching the internetgateway to VPC
    Properties:
      VpcId: !Ref VPC    
      InternetGatewayId: !Ref InternetGateway  
       
  InternetRoute:
    Type: AWS::EC2::Route
    Description: Internet Routetable
    DependsOn:
      - InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref VPCRouteTable
      GatewayId: !Ref InternetGateway
      DestinationCidrBlock: 0.0.0.0/0

  SubnetRouteTableAsso:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Description: Associating the routetable with subnet
    Properties:
      SubnetId: !Ref VPCSubnet
      RouteTableId: !Ref VPCRouteTable

  Instance:
    Type: AWS::EC2::Instance 
    DependsOn:
      - InternetRoute
      - SubnetRouteTableAsso
    Properties:
      InstanceType: t2.micro
      SubnetId: !Ref VPCSubnet
      ImageId: ami-0c7217cdde317cfec
      SecurityGroupIds:
        -
          !Ref EC2SecurityGroup
  
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup 
    Properties:
      GroupDescription:  security group for machine
      VpcId: !Ref VPC
      SecurityGroupIngress:
        -
          CidrIp: 0.0.0.0/0 
          IpProtocol: icmp
          FromPort: -1
          ToPort: -1